version: v2
managed:
  enabled: true
  disable:
    - file_option: go_package_prefix
      module: buf.build/googleapis/googleapis
  override:
    - file_option: go_package_prefix
      value: github.com/farhaan/protoc-gen-go-http-server-interface/examples/editions/tasks/pb
    - file_option: go_package
      path: task.proto
      value: github.com/farhaan/protoc-gen-go-http-server-interface/examples/editions/tasks/pb;pb
plugins:
  - remote: buf.build/protocolbuffers/go
    out: pb
    opt: paths=source_relative
  - local: protoc-gen-go-http-server-interface
    out: pb
    opt:
      - paths=source_relative
      - editions=true
inputs:
  - directory: proto
